web:
  flutter run -d web-server --web-hostname 127.0.0.1 --web-port 5173

linux:
  flutter run -d Linux 

android:
  adb reverse tcp:8080 tcp:8080
  flutter run -d CPH2465

test-watch:
  watchexec -e dart -c -w lib -w test -- flutter test --reporter compact

gen-icons:
  flutter pub run flutter_launcher_icons
